window.EK_INIT=function(slug){
const $=id=>document.getElementById(id); const n=id=>Number($(id)?.value); const out=$('out'); const result=x=>{out.innerHTML=x};
if(slug==='percentage'){$('go').onclick=()=>{const a=n('a'),b=n('b');result(b===0||!Number.isFinite(a)||!Number.isFinite(b)?'<span class="error">Enter two valid numbers; the whole cannot be zero.</span>':`${((a/b)*100).toFixed(2)}%`)}}
if(slug==='tip'){$('go').onclick=()=>{const bill=n('bill'),tip=n('tiprate'),people=Math.max(1,Math.floor(n('people'))||1);if(bill<0||tip<0)return result('<span class="error">Enter valid non-negative values.</span>');const t=bill*tip/100,total=bill+t;result(`Tip: ${t.toFixed(2)}<br>Total: ${total.toFixed(2)}<br>Per person: ${(total/people).toFixed(2)}`)}}
if(slug==='age'){$('go').onclick=()=>{const b=new Date($('birth').value),now=new Date();if(isNaN(b)||b>now)return result('<span class="error">Enter a valid past birth date.</span>');let y=now.getFullYear()-b.getFullYear(),m=now.getMonth()-b.getMonth(),d=now.getDate()-b.getDate();if(d<0){m--;d+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}result(`${y} years, ${m} months, ${d} days`)}}
if(slug==='date-diff'){$('go').onclick=()=>{const a=new Date($('start').value),b=new Date($('end').value);if(isNaN(a)||isNaN(b))return result('<span class="error">Choose both dates.</span>');const days=Math.round(Math.abs(b-a)/86400000);result(`${days.toLocaleString()} day${days===1?'':'s'} between the dates.`)}}
if(slug==='units'){$('go').onclick=()=>{const v=n('value'),from=$('from').value,to=$('to').value;if(!Number.isFinite(v))return result('<span class="error">Enter a number.</span>');const f={m:1,km:1000,cm:.01,mi:1609.344,ft:.3048,kg:1,g:.001,lb:.45359237,c:1};let x=v;if(from==='c'&&to==='f')x=v*9/5+32;else if(from==='f'&&to==='c')x=(v-32)*5/9;else if(from==='c'&&to==='c')x=v;else if(from==='f'&&to==='f')x=v;else if(f[from]&&f[to])x=v*f[from]/f[to];else return result('Choose compatible units.');result(`${x.toLocaleString(undefined,{maximumFractionDigits:8})} ${to}`)}}
if(slug==='words'){$('go').onclick=()=>{const t=$('text').value.trim(),words=t?t.split(/\s+/).length:0,chars=$('text').value.length,charsNo=$('text').value.replace(/\s/g,'').length,sents=t?t.split(/[.!?]+/).filter(Boolean).length:0,paras=t?t.split(/\n\s*\n/).filter(Boolean).length:0;result(`Words: ${words}<br>Characters: ${chars}<br>Characters without spaces: ${charsNo}<br>Sentences: ${sents}<br>Paragraphs: ${paras}`)}}
if(slug==='case'){$('go').onclick=()=>{const t=$('text').value,mode=$('mode').value;let r=t;if(mode==='upper')r=t.toUpperCase();if(mode==='lower')r=t.toLowerCase();if(mode==='title')r=t.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());if(mode==='sentence')r=t.toLowerCase().replace(/(^|[.!?]\s+)\p{L}/gu,m=>m.toUpperCase());$('output').value=r;result('<span class="success">Converted. Your text is in the box above.</span>')}}
if(slug==='password'){$('go').onclick=()=>{const len=Math.min(128,Math.max(4,Math.floor(n('len'))||16)),sets=[...($('lower').checked?'abcdefghijklmnopqrstuvwxyz':''),...($('upper').checked?'ABCDEFGHIJKLMNOPQRSTUVWXYZ':''),...($('nums').checked?'0123456789':''),...($('symbols').checked?'!@#$%^&*()-_=+[]{}?':'')];if(!sets.length)return result('<span class="error">Select at least one character set.</span>');let r='';const a=new Uint32Array(len);crypto.getRandomValues(a);for(let i=0;i<len;i++)r+=sets[a[i]%sets.length];$('output').value=r;result('<span class="success">Generated locally in your browser.</span>')}}
if(slug==='random'){$('go').onclick=()=>{let min=Math.ceil(n('min')),max=Math.floor(n('max'));if(!Number.isFinite(min)||!Number.isFinite(max)||min>max)return result('<span class="error">Enter a valid range.</span>');const a=new Uint32Array(1);crypto.getRandomValues(a);const r=min+Math.floor((a[0]/4294967296)*(max-min+1));result(String(r))}}
if(slug==='slug'){$('go').onclick=()=>{const t=$('text').value.trim().toLowerCase();const r=t.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');$('output').value=r;result('<span class="success">Slug created.</span>')}}
if(slug==='loan'||slug==='mortgage'){$('go').onclick=()=>{const P=n('principal'),annual=n('rate'),years=n('years');if(P<0||annual<0||years<=0)return result('<span class="error">Enter valid non-negative loan details.</span>');const r=annual/100/12,N=Math.round(years*12),pay=r===0?P/N:P*r/(1-Math.pow(1+r,-N));result(`Monthly payment: ${pay.toFixed(2)}<br>Total paid: ${(pay*N).toFixed(2)}<br>Estimated interest: ${(pay*N-P).toFixed(2)}`)}}
if(slug==='compound-interest'){$('go').onclick=()=>{const P=n('principal'),rate=n('rate')/100,years=n('years'),freq=n('freq');if(P<0||years<0||freq<=0||!Number.isFinite(P)||!Number.isFinite(rate))return result('<span class="error">Enter valid values.</span>');const v=P*Math.pow(1+rate/freq,freq*years);result(`Future value: ${v.toFixed(2)}<br>Interest earned: ${(v-P).toFixed(2)}`)}}
if(slug==='discount'){$('go').onclick=()=>{const p=n('price'),d=n('discount');if(p<0||d<0||d>100)return result('<span class="error">Use a price of 0 or more and a discount from 0% to 100%.</span>');const save=p*d/100;result(`You save: ${save.toFixed(2)}<br>Sale price: ${(p-save).toFixed(2)}`)}}
if(slug==='sales-tax'){$('go').onclick=()=>{const p=n('price'),t=n('tax');if(p<0||t<0)return result('<span class="error">Enter valid non-negative values.</span>');const tax=p*t/100;result(`Tax: ${tax.toFixed(2)}<br>Total: ${(p+tax).toFixed(2)}`)}}
if(slug==='gpa'){$('go').onclick=()=>{const g=$('grades').value.split(/[\s,]+/).filter(Boolean).map(Number),c=$('credits').value.split(/[\s,]+/).filter(Boolean).map(Number);if(!g.length||g.length!==c.length||g.some(x=>!Number.isFinite(x))||c.some(x=>!Number.isFinite(x)||x<=0))return result('<span class="error">Enter matching valid grade points and credits.</span>');const total=c.reduce((a,b)=>a+b,0),gp=g.reduce((a,x,i)=>a+x*c[i],0);result(`Weighted GPA: ${(gp/total).toFixed(2)}<br>Total credits: ${total}`)}}
if(slug==='time-calculator'){$('go').onclick=()=>{const a=n('h1')*3600+n('m1')*60+n('s1'),b=n('h2')*3600+n('m2')*60+n('s2'),x=$('op').value==='add'?a+b:a-b,sg=x<0?'-':'',q=Math.abs(x),h=Math.floor(q/3600),m=Math.floor(q%3600/60),sec=q%60;result(`${sg}${h}h ${m}m ${sec}s`)}}
if(slug==='hours-minutes'){$('go').onclick=()=>{const h=n('hours');if(!Number.isFinite(h))return result('<span class="error">Enter decimal hours.</span>');const sign=h<0?'-':'',q=Math.abs(h),hh=Math.floor(q),mm=Math.round((q-hh)*60);result(`${sign}${hh} hours ${mm} minutes`)}}
if(slug==='date-calculator'){$('go').onclick=()=>{const d=new Date($('date').value+'T12:00:00'),days=n('days');if(isNaN(d)||!Number.isFinite(days))return result('<span class="error">Choose a valid date and number of days.</span>');d.setDate(d.getDate()+Math.trunc(days));result(d.toLocaleDateString(undefined,{year:'numeric',month:'long',day:'numeric'}))}}
if(slug==='bmi'){$('go').onclick=()=>{const w=n('weight'),h=n('height')/100;if(w<=0||h<=0)return result('<span class="error">Enter valid height and weight.</span>');const bmi=w/(h*h),cat=bmi<18.5?'Underweight':bmi<25?'Healthy range':bmi<30?'Overweight':'Obesity range';result(`BMI: ${bmi.toFixed(1)}<br>${cat}`)}}
if(slug==='calorie'){$('go').onclick=()=>{const age=n('age'),w=n('weight'),h=n('height'),sex=$('sex').value,act=n('activity');if(age<=0||w<=0||h<=0)return result('<span class="error">Enter valid details.</span>');const bmr=10*w+6.25*h-5*age+(sex==='male'?5:-161),daily=bmr*act;result(`Estimated BMR: ${Math.round(bmr)} kcal/day<br>Estimated daily needs: ${Math.round(daily)} kcal/day`)}}
if(slug==='fuel-cost'){$('go').onclick=()=>{const d=n('distance'),e=n('efficiency'),p=n('price');if(d<0||e<=0||p<0)return result('<span class="error">Enter valid trip details.</span>');const liters=d*e/100;result(`Fuel used: ${liters.toFixed(2)} L<br>Estimated cost: ${(liters*p).toFixed(2)}`)}}
if(slug==='electricity-cost'){$('go').onclick=()=>{const w=n('watts'),h=n('hours'),d=n('days'),r=n('rate');if(w<0||h<0||d<0||r<0)return result('<span class="error">Enter valid values.</span>');const kwh=w/1000*h*d;result(`Energy: ${kwh.toFixed(2)} kWh<br>Estimated cost: ${(kwh*r).toFixed(2)}`)}}
if(slug==='investment-return'){$('go').onclick=()=>{const P=n('principal'),r=n('rate')/100,y=n('years');if(P<0||y<0||!Number.isFinite(r))return result('<span class="error">Enter valid values.</span>');const v=P*Math.pow(1+r,y);result(`Future value: ${v.toFixed(2)}<br>Estimated gain: ${(v-P).toFixed(2)}`)}}
if(slug==='percentage-change'){$('go').onclick=()=>{const a=n('old'),b=n('new');if(a===0||!Number.isFinite(a)||!Number.isFinite(b))return result('<span class="error">Original value must be non-zero.</span>');const c=(b-a)/Math.abs(a)*100;result(`${c>=0?'+':''}${c.toFixed(2)}% ${c>=0?'increase':'decrease'}`)}}
if(slug==='fraction'){$('go').onclick=()=>{let an=Math.trunc(n('aN')),ad=Math.trunc(n('aD')),bn=Math.trunc(n('bN')),bd=Math.trunc(n('bD')),op=$('op').value;if(!ad||!bd||(op==='/'&&!bn))return result('<span class="error">Use non-zero denominators and a non-zero divisor.</span>');let x,y;if(op==='+'){x=an*bd+bn*ad;y=ad*bd}else if(op==='-'){x=an*bd-bn*ad;y=ad*bd}else if(op==='*'){x=an*bn;y=ad*bd}else{x=an*bd;y=ad*bn}const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);const g=gcd(x,y);x/=g;y/=g;if(y<0){x=-x;y=-y}result(`${x}/${y}`)}}
if(slug==='average'){$('go').onclick=()=>{const a=$('numbers').value.split(/[\s,]+/).filter(Boolean).map(Number);if(!a.length||a.some(x=>!Number.isFinite(x)))return result('<span class="error">Enter valid numbers.</span>');const total=a.reduce((x,y)=>x+y,0);result(`Average: ${(total/a.length).toFixed(4)}<br>Count: ${a.length}<br>Total: ${total}`)}}
if(slug==='ratio'){$('go').onclick=()=>{const a=n('a'),b=n('b');if(!Number.isFinite(a)||!Number.isFinite(b)||a===0&&b===0)return result('<span class="error">Enter two valid values.</span>');const scale=1000000,ai=Math.round(a*scale),bi=Math.round(b*scale),g=(x,y)=>y?g(y,x%y):Math.abs(x),d=g(ai,bi);result(`Simplified ratio: ${ai/d}:${bi/d}<br>Relationship: ${(a/b).toFixed(4)}`)}}
if(slug==='random-number'){$('go').onclick=()=>{const min=Math.ceil(n('min')),max=Math.floor(n('max'));if(!Number.isFinite(min)||!Number.isFinite(max)||min>max)return result('<span class="error">Enter a valid range.</span>');const a=new Uint32Array(1);crypto.getRandomValues(a);result(String(min+Math.floor((a[0]/4294967296)*(max-min+1))) )}}
if(slug==='qr-code'){$('go').onclick=async()=>{const t=$('text').value.trim();if(!t)return result('<span class="error">Enter text or a URL.</span>');result('<span>Creating QR code…</span>');try{if(!window.QRCode){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js';s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}out.innerHTML='<div id="qr" style="display:flex;justify-content:center;padding:8px"></div>';new QRCode(document.getElementById('qr'),{text:t,width:220,height:220})}catch(e){result('<span class="error">QR library could not load. Check your internet connection.</span>')}}}
};
