window.EK_INIT=function(slug){const $=id=>document.getElementById(id);const n=id=>Number($(id)?.value);const out=$('out');const result=x=>{out.innerHTML=x};
if(slug==='percentage'){$('go').onclick=()=>{const a=n('a'),b=n('b');result(b===0||!Number.isFinite(a)||!Number.isFinite(b)?'<span class="error">Enter two valid numbers; the whole cannot be zero.</span>':`${((a/b)*100).toFixed(2)}%`)}}
if(slug==='tip'){$('go').onclick=()=>{const bill=n('bill'),tip=n('tiprate'),people=Math.max(1,Math.floor(n('people'))||1);if(bill<0||tip<0)return result('<span class="error">Enter valid non-negative values.</span>');const t=bill*tip/100,total=bill+t;result(`Tip: ${t.toFixed(2)}<br>Total: ${total.toFixed(2)}<br>Per person: ${(total/people).toFixed(2)}`)}}
if(slug==='age'){$('go').onclick=()=>{const b=new Date($('birth').value),now=new Date();if(isNaN(b)||b>now)return result('<span class="error">Enter a valid past birth date.</span>');let y=now.getFullYear()-b.getFullYear(),m=now.getMonth()-b.getMonth(),d=now.getDate()-b.getDate();if(d<0){m--;d+=new Date(now.getFullYear(),now.getMonth(),0).getDate()}if(m<0){y--;m+=12}result(`${y} years, ${m} months, ${d} days`)}}
if(slug==='date-diff'){$('go').onclick=()=>{const a=new Date($('start').value),b=new Date($('end').value);if(isNaN(a)||isNaN(b))return result('<span class="error">Choose both dates.</span>');const days=Math.round(Math.abs(b-a)/86400000);result(`${days.toLocaleString()} day${days===1?'':'s'} between the dates.`)}}
if(slug==='units'){$('go').onclick=()=>{const v=n('value'),from=$('from').value,to=$('to').value;if(!Number.isFinite(v))return result('<span class="error">Enter a number.</span>');const f={m:1,km:1000,cm:.01,mi:1609.344,ft:.3048,kg:1,g:.001,lb:.45359237,c:1};let x=v;if(from==='c'&&to==='f')x=v*9/5+32;else if(from==='f'&&to==='c')x=(v-32)*5/9;else if(from==='c'&&to==='c')x=v;else if(from==='f'&&to==='f')x=v;else if(f[from]&&f[to])x=v*f[from]/f[to];else return result('Choose compatible units.');result(`${x.toLocaleString(undefined,{maximumFractionDigits:8})} ${to}`)}}
if(slug==='words'){$('go').onclick=()=>{const t=$('text').value.trim(),words=t?t.split(/\s+/).length:0,chars=$('text').value.length,charsNo=$('text').value.replace(/\s/g,'').length,sents=t?t.split(/[.!?]+/).filter(Boolean).length:0,paras=t?t.split(/\n\s*\n/).filter(Boolean).length:0;result(`Words: ${words}<br>Characters: ${chars}<br>Characters without spaces: ${charsNo}<br>Sentences: ${sents}<br>Paragraphs: ${paras}`)}}
if(slug==='case'){$('go').onclick=()=>{const t=$('text').value,mode=$('mode').value;let r=t;if(mode==='upper')r=t.toUpperCase();if(mode==='lower')r=t.toLowerCase();if(mode==='title')r=t.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());if(mode==='sentence')r=t.toLowerCase().replace(/(^|[.!?]\s+)\p{L}/gu,m=>m.toUpperCase());$('output').value=r;result('<span class="success">Converted. Your text is in the box above.</span>')}}
if(slug==='password'){$('go').onclick=()=>{const len=Math.min(128,Math.max(4,Math.floor(n('len'))||16)),sets=[...($('lower').checked?'abcdefghijklmnopqrstuvwxyz':''),...($('upper').checked?'ABCDEFGHIJKLMNOPQRSTUVWXYZ':''),...($('nums').checked?'0123456789':''),...($('symbols').checked?'!@#$%^&*()-_=+[]{}?':'' )];if(!sets.length)return result('<span class="error">Select at least one character set.</span>');let r='';const a=new Uint32Array(len);crypto.getRandomValues(a);for(let i=0;i<len;i++)r+=sets[a[i]%sets.length];$('output').value=r;result('<span class="success">Generated locally in your browser.</span>')}}
if(slug==='random'){$('go').onclick=()=>{let min=Math.ceil(n('min')),max=Math.floor(n('max'));if(!Number.isFinite(min)||!Number.isFinite(max)||min>max)return result('<span class="error">Enter a valid range.</span>');const a=new Uint32Array(1);crypto.getRandomValues(a);const r=min+Math.floor((a[0]/4294967296)*(max-min+1));result(String(r))}}
if(slug==='slug'){$('go').onclick=()=>{const t=$('text').value.trim().toLowerCase();const r=t.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'');$('output').value=r;result('<span class="success">Slug created.</span>')}}};